---
- name: Map EPGs to ports
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no


  tasks:

  - name: Deploy Static Path binding for EPG
    cisco.aci.aci_static_binding_to_epg:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"
      epg: "{{ item.epg }}"
      encap_id: "{{ item.vlan }}"
      deploy_immediacy: lazy
      interface_mode: "{{ item.int_mode }}"
      interface_type: "{{ item.int_type }}"
      pod_id: "{{ pod }}"
      interface: "{{ item.interface }}"
      leafs: "{{ item.leaf }}"
    loop:
      "{{ epg_ports }}"
